# 1a: 
__Q:__ In the perceptron below, what will the output be when the input is (0, 0)? What about inputs (0, 1), (1, 1) and (1, 0)? What if we change the bias weight to -0.5? <br>

__A:__<br>


In [1]:
import numpy as np

inputs = np.array(((0,0, 1), (0, 1, 1), (1,0, 1), (1,1,1))).T
print(inputs)
weights = np.array((1, 1, -1.5))
total  = np.dot(weights,inputs)
print('\n ',total)

weights = np.array((1, 1, -0.5))
total  = np.dot(weights,inputs)
print('\n ',total)


[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

  [-1.5 -0.5 -0.5  0.5]

  [-0.5  0.5  0.5  1.5]


Output = 1 if element larger than 1.

# 1b
__Q:__ Starting with random weights, how do you proceed in order to train the perceptron above to perform any given
binary operation? Explain. <br>

__A:__ We have $$Error = target - output.$$
The weights are then adjusted according to $$\Delta \omega_i = \eta*Error*x_i $$

# 1c
__Q:__ Implement the perceptron, and train it to perform the logical functions NOT (use only one of the inputs), NAND,
and NOR. What happens when you try to train it do the XOR function?

In [2]:
class SingleLayerPerceptron:
    """ 
    Single output node
    Inputs argument must be a matrix with one input vector per column
    """
    
    def __init__(self, inputs, maxIterations, trueFunction, tolerance, learningRate):
        self.inputs = inputs
        self.numberOfInputs = np.shape(self.inputs)[1]
        self.maxIterations = maxIterations
        self.trueFunction = trueFunction
        self.tolerance = tolerance
        self.learningRate = learningRate
        
    def runNetwork(self):
        self.initializeWeights()
        self.iterationNumber = 0
        numberOfAdjustmentsDuringIteration = 1
        while (self.iterationNumber < self.maxIterations and numberOfAdjustmentsDuringIteration != 0):
            self.iterationNumber += 1
            numberOfAdjustmentsDuringIteration = 0
            
            for inputNumber in range(self.numberOfInputs):
                self.inputVector = self.inputs[:,inputNumber]
                self.weighInput()
                self.thresholding()
                self.calculateTarget()
                self.calculateError()

                if abs(self.error) > self.tolerance:
                    numberOfAdjustmentsDuringIteration +=1
                    self.adjustWeights()
       
        self.printFinalWeights()
                    
        
    def initializeWeights(self):
        np.random.seed(1)
        numberOfWeights = np.shape(self.inputs)[0]
        self.weights = np.random.uniform(-.25, .25, (1,numberOfWeights))
        
        
    def weighInput(self):
        self.weightedInput = np.asscalar(np.dot(self.weights, self.inputVector))
        
    def thresholding(self):
        if self.weightedInput > 0: 
            self.output = 1
        else:
            self.output = 0
            
    def calculateTarget(self):
        self.target = self.trueFunction(self.inputVector[1:])
        
    def calculateError(self):
        self.error =  self.target - self.output
    
    def adjustWeights(self):
        deltaWeights = self.learningRate*self.error*self.inputVector
        self.weights += deltaWeights
        
    def printFinalWeights(self):
        print('\n Weights: \n', self.weights, '\n Number of iterations: ', self.iterationNumber)
        
    def predict(self, newInput):
        self.inputVector = newInput
        self.weighInput()
        self.thresholding()
        print('Input: ', newInput, 'Predicted output: ', self.output)

In [12]:
class Problem:    
    """ Based on input vetors and a function, the class SingleLayerPerceptron is called upon and run """
    def __init__(self, function, inputs):
        self.function, self.inputs = function, inputs
        #print('inputs iun problem', inputs)

    def solve(self):
        print("\n Function: ", self.function.__name__)
        maxIterations = 1000
        tolerance = 1e-12
        learningRate = 1e-1
        
        tst= SingleLayerPerceptron(self.inputs, maxIterations, self.function, tolerance, learningRate)
        tst.runNetwork()
        
        for i in range(np.shape(self.inputs)[1]):
            tst.predict(self.inputs[:,i])
         
        #testArray = np.array((-1, 0.2, 1.5))
        #tst.predict(testArray)

In [13]:
# The exercise examples
inputs = np.array(((-1,0, 0), (-1, 0, 1), (-1,1, 0), (-1,1,1))).T
inputNot = np.array(((-1,0), (-1,1))).T

def nand(array):
    if (array[0] == 1 and array[1] == 1):
        output  = 0
    else:
        output = 1
    return output

def nor(array):
    if (array[0] == 0 and array[1] == 0):
        return 1
    else:
        return 0

def notFunction(scalar):
    if scalar == 0:
        return 1
    else:
        return 0
    
def xor(array):
    if (array[0] == 0 and array[1] == 0):
        output = 0
    elif (array[0] == 0 and array[1] == 1):
        output = 1
    elif (array[0] == 1 and array[1] == 0):
        output = 1
    elif (array[0] == 1 and array[1] == 1):
        output = 0
    return output
    

inputList = inputs, inputs, inputNot, inputs
functionList = nand, nor, notFunction, xor

for inputNumber, functionNumber in zip(inputList, functionList):
    #print('inputNumber', inputNumber)
    p1 = Problem(functionNumber, inputNumber)
    p1.solve()

print('\n NAND TRUE')
for i in range(4):
    print('Input: ', inputs[1:,i], 'True :', nor(inputs[1:,i],))


 Function:  nand

 Weights: 
 [[-0.341489   -0.28983775 -0.14994281]] 
 Number of iterations:  9
Input:  [-1  0  0] Predicted output:  1
Input:  [-1  0  1] Predicted output:  1
Input:  [-1  1  0] Predicted output:  1
Input:  [-1  1  1] Predicted output:  0

 Function:  nor

 Weights: 
 [[-0.041489   -0.08983775 -0.24994281]] 
 Number of iterations:  4
Input:  [-1  0  0] Predicted output:  1
Input:  [-1  0  1] Predicted output:  0
Input:  [-1  1  0] Predicted output:  0
Input:  [-1  1  1] Predicted output:  0

 Function:  notFunction

 Weights: 
 [[-0.041489   -0.08983775]] 
 Number of iterations:  4
Input:  [-1  0] Predicted output:  1
Input:  [-1  1] Predicted output:  0

 Function:  xor

 Weights: 
 [[-0.041489   -0.08983775 -0.14994281]] 
 Number of iterations:  1000
Input:  [-1  0  0] Predicted output:  1
Input:  [-1  0  1] Predicted output:  0
Input:  [-1  1  0] Predicted output:  0
Input:  [-1  1  1] Predicted output:  0

 NAND TRUE
Input:  [0 0] True : 1
Input:  [0 1] True : 0


XOR does not have a converging solution, the other functions is correctly approximated.