# 1a: 
__Q:__ In the perceptron below, what will the output be when the input is (0, 0)? What about inputs (0, 1), (1, 1) and (1, 0)? What if we change the bias weight to -0.5? <br>

__A:__<br>


In [84]:
import numpy as np

inputs = np.array(((0,0, 1), (0, 1, 1), (1,0, 1), (1,1,1))).T
print(inputs)
weights = np.array((1, 1, -1.5))
total  = np.dot(weights,inputs)
print('\n ',total)

weights = np.array((1, 1, -0.5))
total  = np.dot(weights,inputs)
print('\n ',total)


[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

  [-1.5 -0.5 -0.5  0.5]

  [-0.5  0.5  0.5  1.5]


Output = 1 if element larger than 1.

# 1b
__Q:__ Starting with random weights, how do you proceed in order to train the perceptron above to perform any given
binary operation? Explain. <br>

__A:__ We have $$Error = target - output.$$
The weights are then adjusted according to $$\Delta \omega_i = \eta*Error*x_i $$

# 1c
__Q:__ Implement the perceptron, and train it to perform the logical functions NOT (use only one of the inputs), NAND,
and NOR. What happens when you try to train it do the XOR function?

In [94]:
nand = lambda array: 0 if (array[0] == 1 and array[1] == 1) else 1

class SingleLayerPercectron:
    def __init__(self, inputs, maxIterations):
        self.inputs = inputs
        self.numberOfInputs = np.shape(self.inputs)[1]
        self.maxIterations = maxIterations
        
    def runNetwork(self):
        self.initializeWeights()
        tolerance = 1e-7
        for i in range(maxIterations):
            for inputNumber in range(self.numberOfInputs):
                self.inputVector = self.inputs[:,inputNumber]
                self.weightedInput()
                self.thresholding()
                self.calculateTarget()
                self.calculateError()
                if self.error > tolerance:
                    adjustWeights
        self.printFinalWeights()
                    
        
    def initializeWeights(self):
        numberOfWeights = np.shape(self.inputs)[0]
        self.weights = np.random.uniform(-.25, .25, (1,numberOfWeights))
        
        
    def weightedInput(self):
        self.weightedInput = np.dot(self.inputVector,self.weights)
        
    def thresholding(self):
        if self.weightedInput >= 0: 
            self.output = 1
        else:
            self.output = 0
            
    def calculateTarget(self):
        self.target = self.trueFunction(self.weightedInput[1:])

    def calculateError(self):
        self.error =  self.target - self.output
    
    def adjustWeights(self):
        learningRate = .25
        deltaWeights = learningRate*self.error*self.inputVector
        self.weights += deltaWeights
        
    def printFinalWeights(self):
        print(self.weights)
        
    
maxIterations = 10
inputs = np.array(((-1,0, 0), (-1, 0, 1), (-1,1, 0), (-1,1,1))).T
tst= SingleLayerPercectron(inputs, maxIterations)
#tst.initializeWeights()
#tst.weights
#tst.printFinalWeights()
tst.runNetwork()

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)