# 1a: 
__Q:__ In the perceptron below, what will the output be when the input is (0, 0)? What about inputs (0, 1), (1, 1) and (1, 0)? What if we change the bias weight to -0.5? <br>

__A:__<br>


In [1]:
import numpy as np

inputs = np.array(((0,0, 1), (0, 1, 1), (1,0, 1), (1,1,1))).T
print(inputs)
weights = np.array((1, 1, -1.5))
total  = np.dot(weights,inputs)
print('\n ',total)

weights = np.array((1, 1, -0.5))
total  = np.dot(weights,inputs)
print('\n ',total)


[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

  [-1.5 -0.5 -0.5  0.5]

  [-0.5  0.5  0.5  1.5]


Output = 1 if element larger than 1.

# 1b
__Q:__ Starting with random weights, how do you proceed in order to train the perceptron above to perform any given
binary operation? Explain. <br>

__A:__ We have $$Error = target - output.$$
The weights are then adjusted according to $$\Delta \omega_i = \eta*Error*x_i $$

# 1c
__Q:__ Implement the perceptron, and train it to perform the logical functions NOT (use only one of the inputs), NAND,
and NOR. What happens when you try to train it do the XOR function?

In [19]:
class SingleLayerPercectron:
    def __init__(self, inputs, maxIterations, trueFunction, tolerance, learningRate):
        self.inputs = inputs
        self.numberOfInputs = np.shape(self.inputs)[1]
        self.maxIterations = maxIterations
        self.trueFunction = trueFunction
        self.tolerance = tolerance
        self.learningRate = learningRate
        
    def runNetwork(self):
        self.initializeWeights()
        self.iterationNumber = 0
        numberOfAdjustmentsDuringIteration = 1
        while (self.iterationNumber < self.maxIterations and numberOfAdjustmentsDuringIteration != 0):
            self.iterationNumber += 1
        #for self.iterationNumber in range(self.maxIterations):
            #print('\n iteration ', self.iterationNumber)
            numberOfAdjustmentsDuringIteration = 0
            results = np.zeros(self.numberOfInputs)
            targets = np.zeros(self.numberOfInputs)
            inputsLast = []
            inputToFunction = []

            for inputNumber in range(self.numberOfInputs):
                #print('\n inputNumber ', inputNumber)
                self.inputVector = self.inputs[:,inputNumber]
                #print('input vector', self.inputVector)
                self.weighInput()
                self.thresholding()
               
                results[inputNumber] = self.output
                
                self.calculateTarget()
                
                targets[inputNumber] = self.target
                inputsLast.append(self.inputVector)
                inputToFunction.append(self.inputVector[1:])

                self.calculateError()

                if abs(self.error) > self.tolerance:
                    #print('Adjusting')
                    numberOfAdjustmentsDuringIteration +=1
                    self.adjustWeights()
        print('results last ', results, '\n target last: ', targets, '\n inputs last: ', inputsLast, \
             '\n input to function ', inputToFunction)
        self.printFinalWeights()
                    
        
    def initializeWeights(self):
        np.random.seed(1)
        numberOfWeights = np.shape(self.inputs)[0]
        self.weights = np.random.uniform(-.25, .25, (1,numberOfWeights))
        
        
    def weighInput(self):
        self.weightedInput = np.asscalar(np.dot(self.weights, self.inputVector))
        
    def thresholding(self):
        if self.weightedInput >= 0: 
            self.output = 1
        else:
            self.output = 0
            
    def calculateTarget(self):
        self.target = self.trueFunction(self.inputVector[1:])

    def calculateError(self):
        self.error =  self.target - self.output
    
    def adjustWeights(self):
        deltaWeights = self.learningRate*self.error*self.inputVector
        self.weights += deltaWeights
        
    def printFinalWeights(self):
        print('\n Weights: \n', self.weights, '\n Number of iterations: ', self.iterationNumber)
        
    def predict(self, newInput):
        self.inputVector = newInput
        self.weighInput()
        self.thresholding()
        print('Input: ', newInput, 'Predicted output: ', self.output)
        
class Problem:    
    def __init__(self, function, inputs):
        self.function, self.inputs = function, inputs

    def solve(self):
        print("Function: ", self.function.__name__)
        maxIterations = 20
        tolerance = 1e-12
        learningRate = .1
        
        tst= SingleLayerPercectron(inputs, maxIterations, nand, tolerance, learningRate)
        tst.runNetwork()
        print('Error last: ', tst.error)

        for i in range(np.shape(inputs)[1]):
            tst.predict(inputs[:,i])


inputs = np.array(((-1,0, 0), (-1, 0, 1), (-1,1, 0), (-1,1,1))).T
nand = lambda array: 0 if (array[0] == 1 and array[1] == 1) else 1    
nor = lambda array: 1 if (array[0] == 0 and array[1] == 0) else 0



p1 = Problem(nor, inputs)
p1.solve()

print('\n')
for i in range(4):
    print('Input: ', inputs[1:,i], 'True :', nor(inputs[1:,i],))

Function:  <lambda>
results last  [1. 1. 1. 0.] 
 target last:  [1. 1. 1. 0.] 
 inputs last:  [array([-1,  0,  0]), array([-1,  0,  1]), array([-1,  1,  0]), array([-1,  1,  1])] 
 input to function  [array([0, 0]), array([0, 1]), array([1, 0]), array([1, 1])]

 Weights: 
 [[-0.341489   -0.28983775 -0.14994281]] 
 Number of iterations:  9
Error last:  0
Input:  [-1  0  0] Predicted output:  1
Input:  [-1  0  1] Predicted output:  1
Input:  [-1  1  0] Predicted output:  1
Input:  [-1  1  1] Predicted output:  0


Input:  [0 0] True : 1
Input:  [0 1] True : 0
Input:  [1 0] True : 0
Input:  [1 1] True : 0
