## Exercise 1 Representations and their operators for crossover and mutation

__Binary:__ 
<br>
On the computer. Spices example. Each gene represents one spice, and the value can be true or false.
<br>

Mutation:<br> 
Bit-flip. With a probability $p_m$ flip one, or several, digits.
<br>

Recombination:<br>  
L#2 s. 32-: Single-point crossover, n-point crossover, uniform crossover (Tail = parent 1, heads = parent 2, flip through each gene. Child 2 opposite of child 1.)
<br>

__Integer:__ 
<br>
TSP problem, 8 queens chess problem. Vector of different integers, <mark> DIP, colors (red, blue)
<br>
Mutation: <br>
Creeping (slow) or resetting (larger change)
<br>
Crossover:<br> 
    N-point, uniform.

__Floating point numbers:__ 
<br>
Maximization of numbers smaller than integers.
<br>
Mutation: Unform mutation, same role as bit flip for bindary or random resetting for integers. Draw from [LB, UB], upper lower bound. 
<br>
Non-uniform mutation: Use gaussian each variable seprately.
<br>
Crossover: <br>
Discrete recombination: Value always from 1 of parents (No averages). n-point crossover or uniform.  
<br>
Intermediate recombination: Children, weighted average of parents, as I did in my 1st EA.
<br>
Example: Simple arithmetic crossover: Crossover + intermediate after crossover point.
<br>
Example: Single arithmetic crossover. Child 1 equal parent 1 to the left of point, at point a weighted average, and parent 2 to the right of point.
<br>
Example: Whole arithmetic crossover: weighted average everywhere.
<br>

__Trees:__ Loops, mathematical expressions.
<br>
Mutation: replace randomly chosen subtree by randomly generated tree
<br>
Crossover: Most common recombination: exchange two randomly chosen subtrees among the parents
<br>

__Permutation:__ 
<br>
Travelling sales person. One number only appears once. List of n different integers.
<br>
Mutation:
    <br>
    Must change at least 2 values. Swapping. Insert mutation: Move one next to another and change all others to come next in same order as they were. Scramble mutation: for certain number of genes randomly reorder these genes. Inversion: For a chosen area, reverse the order of the genes.
 <br>
Crossover:
<br>
   Adjacance important (who is neighbor). TSP. --> Conserve adjacancy.
   <br>
   Partially mapped crossover and edge recombination: L#2 s. 52
   <br>
   Order importan others. Need to conserve order. Order corssover and cycle crossover.
   <br>
   Partially mapped crossover (PMX). See slides L#2 s 56.
   <br>
   Edge recombination. See slide.
   <br>
   Order crossover: L#2 s 61. Understandable example.
   <br>
   Cycle crossover: L#2 s 62. 


## Exercsise 2: Bit flip mutation

In [7]:
import scipy.special

pm = 1./4
p0 = (1 - pm)**4

n = 4
p1 = scipy.special.binom(n, 1)*pm**1*(1-pm)**(n-1)

pMoreThan1 = 0
for k in range(2,4+1):
    pMoreThan1 += scipy.special.binom(n, k)*pm**k*(1-pm)**(n-k)

print('p(0) = ', p0, '\n p(1) = ', p1, '\n p(x>1) = ', pMoreThan1)

p(0) =  0.31640625 
 p(1) =  0.421875 
 p(x>1) =  0.26171875


Altnernatively, $P(x>1) = P(x \geq 2) = 1 - P(0) - P(1)$

## Exercise 3: Crossover
# PMX Example from book first.

In [93]:
p1 = np.asarray(np.arange(1,9+1,1))
p2 = np.asarray((9,3,7,8,2,6,5,1,4))
c = np.zeros(len(p1))
startPosition = 3
stopPosition = 6+1
c[startPosition:stopPosition] = p1[startPosition:stopPosition]
print(c)
for position in np.arange(startPosition,stopPosition,1):
    if p2[position] not in c[startPosition:stopPosition]:
        nextNumber = p2[position]
        childValue = c[position]
        childValueIndexInP2 = np.where(p2 == childValue)
        if childValueIndexInP2 not in c[startPosition:stopPosition]:
            c[childValueIndexInP2] = nextNumber
        else:
            parantPosAlternative = np.where(p2 == c[childValueIndexInP2])
            c[parantPosAlternative] = nextNumber

    
        #print('next number: ', nextNumber)
        #print('childValue', childValue)
        #print('childValueIndexInP2', childValueIndexInP2)
        print('c', c)
        
remainingPositions = np.where( c == 0)
print('c rem',  remainingPositions)
#c[remainingPositions] = p2[remainingPositions]
print('p2', p2)
print('c ', c)

for position in remainingPositions:
    c[position] = p2[position]

print(c)

[0. 0. 0. 4. 5. 6. 7. 0. 0.]
c [0. 0. 0. 4. 5. 6. 7. 0. 8.]
c [0. 0. 2. 4. 5. 6. 7. 0. 8.]
c rem (array([0, 1, 7]),)
p2 [9 3 7 8 2 6 5 1 4]
c  [0. 0. 2. 4. 5. 6. 7. 0. 8.]
[9. 3. 2. 4. 5. 6. 7. 1. 8.]


In [103]:
class Pmx:
    def __init__(self, p1, p2, startPosition, stopPosition):
        self.p1, self.p2, self.startPosition, self.stopPosition =\
        p1, p2, startPosition, stopPosition
        
    def createChild(self):
        p1, p2, startPosition, stopPosition = \
        self.p1, self.p2, self.startPosition, self.stopPosition
        
        c = np.zeros(len(p1))
        c[startPosition:stopPosition] = p1[startPosition:stopPosition]

        for position in np.arange(startPosition,stopPosition,1):
            if p2[position] not in c[startPosition:stopPosition]:
                nextNumber = p2[position]
                childValue = c[position]
                childValueIndexInP2 = np.where(p2 == childValue)
                if childValueIndexInP2 not in c[startPosition:stopPosition]:
                    c[childValueIndexInP2] = nextNumber
                else:
                    parantPosAlternative = np.where(p2 == c[childValueIndexInP2])
                    c[parantPosAlternative] = nextNumber
                    
        remainingPositions = np.where( c == 0)
        for position in remainingPositions:
            c[position] = p2[position]
        return c

In [104]:
p1 = np.asarray(np.arange(1,9+1,1))
p2 = np.asarray((9,3,7,8,2,6,5,1,4))
startPosition = 3
stopPosition = 6+1
pmx = Pmx(p1, p2, startPosition, stopPosition)
child = pmx.createChild()
print(child)

[9. 3. 2. 4. 5. 6. 7. 1. 8.]


In [105]:
# Exercise values
p1 = np.array((2,4,7,1,3,6,8,9,5))
p2 = np.array((5,9,8,6,2,4,1,3,7))
startPosition = 3
stopPosition = 6+1
pmx = Pmx(p1, p2, startPosition, stopPosition)
child = pmx.createChild()
print(child)

[5. 9. 8. 1. 3. 6. 4. 2. 7.]


One element differs from solutions.