# Assignment 2

We start by giving a simple overview of the implementation. Then we will show the necessary vode for applying the NN-class made and the resulting results.

## Performance measure
The model performance is calculated by the accuracy of the estimated model when applied to the test data. The accuracy is the number of correct predictions divided by the number of total observations. <br>

The model output is not on binary form. In order to calculate the accuracy, we transform the model output to binary form by use of the Hard max function. The Hard max function sets the largest element value in the putput vectors equal to one and the other elements to zero. 

## The main algorithm
We will apply the method "solAlg1" from the Neural Network class "nnClass.py". The algorithm goes forward and backward for each observation. Before every epoch the order of the training observations is shuffled. 

## Early stopping
The main algorithm "solAlg1" contains early stopping. The algorithm will run for a chosen number of epochs before the model performance on the validation set is calculated. When the validation set accuracy drops, we stop the training.

## The main algorithm pseudo code
Here follows pseudo code of the main algorithm:

solAlg1:
        
            for trainingCycle in range(trainingCyclesPerValidation):
                shuffle index
                for idx in range(np.shape(self.targetMatrixTrain)[0]):
                    forward
                    backward
            calculate validation set performance
            
            if performance lower than best performance
                break

## Code
The code is found in two files: <br>
1) nnClassRevised.py: contains the Neural network solver class. <br>
2) runAssignment2Revised.py:  contains a function for loading of the assignment data and functions for solving the specific tasks. <br>

We start by importing everything from the above mentioned  files.

In [1]:
from nnClassRevised import *
from runAssignment2Revised import *

"dataAssignment2Revised", which is part of spyderTesting, split the data into training/velidation/test with the corresponding relations 50/25/25 per cent. We will first use this data split when analysing the model performance. By calling the function "dataAssignment2Revised", we load the data for the assignment and split it into test, validation and training sets. "dataAssignment2Revised" is almost identical to the file "movements.py" provided with the assignment.

In [2]:
train, train_targets, valid, valid_targets, test, test_targets = dataAssignment2()

# Hidden nodes. Fixed validation set.
In order to determine the optimal number of hidden nodes, we run the neural network with different number of nodes and study the model performance on validation sets. The solution algorith above is applied. In addition to the main part of the solution algorithm, the algorithm produces confusion matrices and accuracy scores. The implementation and results for different number of hidden nodes now follow. 

In [3]:
activationFunction= 'sigmoid'
trainingCyclesPerValidation = 5
maxValidations= 300
maxLocalOptima = 15
np.random.seed(1)

for numberOfHiddenNodes in 6, 8 ,12:
    fixedValidationSet( train=train,
                       train_targets = train_targets,
                       valid=valid,
                       valid_targets=valid_targets,
                       numberOfHiddenNodes = numberOfHiddenNodes,
                        activationFunction = activationFunction,
                        trainingCyclesPerValidation = trainingCyclesPerValidation,
                        maxValidations = maxValidations,
                        maxLocalOptima = maxLocalOptima)


Hidden nodes:  6
Activation function:  sigmoid
Hidden nodes:  6
Epochs per validation:  5
Best Confusion Matrix: 
 [[0.92 0.   0.   0.   0.08 0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.   0.07 0.21 0.29 0.14 0.   0.14 0.14]
 [0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.08 0.   0.   0.08 0.83 0.   0.  ]
 [0.   0.   0.   0.   0.21 0.11 0.68 0.  ]
 [0.12 0.   0.   0.   0.   0.   0.   0.88]]
Best accuracy: 0.83
TotalNumberOfIterations:  105
Validations:  21

Hidden nodes:  8
Activation function:  sigmoid
Hidden nodes:  8
Epochs per validation:  5
Best Confusion Matrix: 
 [[0.92 0.   0.   0.   0.   0.   0.   0.08]
 [0.   1.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.92 0.   0.   0.   0.   0.08]
 [0.   0.   0.   0.57 0.   0.   0.14 0.29]
 [0.   0.   0.   0.06 0.94 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.   0.   0.   0.16 0.11 0.74 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   1.  ]]
Best accura

__Warning:__ The results change with new runs due to the randomness in the main algorithm. Hence re-running the above code will give different results, especially wrt. the confusion matrix and which classes are worst.<br>

We see that the accuracy lays between 83 and 90 percent, depending on the number of hidden nodes. <br>

The performance increaess with number of hidden nodes. 12 hidden nodes gives 90 percent accuracy on validation.<br>

The number of simulations seems to be about the same irrespective of node numbers. This is a bit surprising, since I would expect a more complex network needing more simulations. <br>

There are four classes that has mis-classifications in the case of 12 nodes. 12 per cent is the largest error. <br>

The mis-classfication pattern differst between the different node numbers.

# K-fold
Next we will apply the K-fold crossvalidation method, which is a resempling method. All the data is divided into $K$ number of folds. For one iteration one of the folds performs as validation set while the remaining folds perform as training set. <br>

K-fold is implemented as an own method in the NN-class. The traning, testing and  validation sets are concatenated to one data set. The resulting data set is then divided into $K$ folds. Each combination of folds are sent into the main solution algorithm descirbed and applied above. Hence we will get $K$ number of results from the $K$-fold analysis.<br>

In order to compare the K-fold method with the fixed validation set method, we choose the same number of epochs per validation and the same limit for worsening solutions. Furthermore we choose $K=3$ so that the size of the training and validation sets mimimcs the size from the previous analysis with fixed training and validation sets.

In [4]:
for numberOfHiddenNodes in 6, 8 ,12:
    print('\n#####################   ', 'Hidden nodes: ', numberOfHiddenNodes, '   ############################')
    runKfold(train=train ,
            train_targets=train_targets,
            valid=valid ,
            valid_targets=valid_targets ,
            
            numberOfHiddenNodes=numberOfHiddenNodes,
            activationFunction= 'sigmoid',
            numberOfFolds = 3, 
            trainingCyclesPerValidation=5,
            maxValidations = 1000,
            maxLocalOptima = 15,
            printConfusionMatrix=False)


#####################    Hidden nodes:  6    ############################

Best accuracy folds:  [0.8067331670822944, 0.835, 0.7196495619524406]
Mean(bestScores): 0.79, std(bestScores) 0.05

#####################    Hidden nodes:  8    ############################

Best accuracy folds:  [0.9364089775561097, 0.805243445692884, 0.87375]
Mean(bestScores): 0.87, std(bestScores) 0.05

#####################    Hidden nodes:  12    ############################

Best accuracy folds:  [0.98, 0.8915211970074813, 0.9011264080100124]
Mean(bestScores): 0.92, std(bestScores) 0.04


We see that the accuracy scores lay in the same area as for the static train/test split, the mean scores being between approximately 80 and 90 per cent. The rankings between the different hidden node numbers are the same as for the static train/test split: the highest node number is still the best, and the lowest node number is now the worst. <br>

The standard deviations gives extra information about the uncertainty of the different scores. We see that the standard deviations are of such order that the confidence intervals do not overlap. Hence the difference in performance between the node numbers seems significant. <br>


# Testing the model
Til now we have studied the optimal number of hidden nodes. Let's see how our model performs on the test set. We apply the highest number of layers, which performed best both with K-fold crossvalidation and with the static train/validation split.

In [5]:
np.random.seed(1)
activationFunction= 'sigmoid'
trainingCyclesPerValidation = 5
maxValidations= 300
maxLocalOptima = 15
numberOfHiddenNodes = 12

runTestSet(train=train,
           train_targets = train_targets,
           valid=valid,
           valid_targets=valid_targets,
           test=test,
           test_targets=test_targets,
           numberOfHiddenNodes = numberOfHiddenNodes,
           activationFunction = activationFunction,
           trainingCyclesPerValidation = trainingCyclesPerValidation,
           maxValidations = maxValidations,
           maxLocalOptima = maxLocalOptima)


Hidden nodes:  12
Activation function:  sigmoid
Hidden nodes:  12
Epochs per validation:  5
Best Confusion Matrix: 
 [[0.85 0.   0.08 0.   0.   0.   0.   0.08]
 [0.   1.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.   0.07 0.29 0.36 0.07 0.   0.07 0.14]
 [0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.   0.   0.   0.05 0.05 0.89 0.  ]
 [0.   0.06 0.   0.   0.   0.   0.   0.94]]
Best accuracy: 0.88
TotalNumberOfIterations:  110
Validations:  22

Test Confusion Matrix: 
 [[1.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.   0.08 0.15 0.15 0.31 0.   0.   0.31]
 [0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.07 0.73 0.2  0.  ]
 [0.   0.11 0.   0.   0.22 0.11 0.56 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   1.  ]]
Best accuracy: 0.83


We see that the accuracy drops from 88 per cent on the validation data to 83 per cent on the test data. The accuracy drop is not surprising. The number of hidden nodes are optimized for the validation data and not for the test data. The largest difference between the validation and test predictions is on class 1, which drops from 94 per cent to 44 per cent when going from validation to test.